// Copies TYPESAFE_API_KEY from .env into src/config.local.js, which the
// extension's service worker imports. Chrome can't read .env files directly,
// so this is the one step between "paste key" and "extension works".
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = resolve(root, ".env");
const outPath = resolve(root, "src", "config.local.js");

if (!existsSync(envPath)) {
  console.error(`No .env found at ${envPath}. Copy .env.example to .env and paste your key after the =.`);
  process.exit(1);
}

const env = {};
for (const raw of readFileSync(envPath, "utf8").split(/\r?\n/)) {
  const line = raw.trim();
  if (!line || line.startsWith("#")) continue;
  const eq = line.indexOf("=");
  if (eq === -1) continue;
  let value = line.slice(eq + 1).trim();
  if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
  env[line.slice(0, eq).trim()] = value;
}

const key = env.TYPESAFE_API_KEY || "";
if (!key) {
  console.error("TYPESAFE_API_KEY is empty in .env. Paste your key after the = and run this again.");
  process.exit(1);
}

writeFileSync(
  outPath,
  `// Generated by scripts/sync-key.mjs from .env. Git-ignored. Do not edit by hand.\nexport const TYPESAFE_API_KEY = ${JSON.stringify(key)};\n`
);
console.log(`Wrote ${outPath} (key ending in ...${key.slice(-4)}).`);

console.log("Now reload the extension at chrome://extensions (or load it unpacked for the first time).");
